---

# Quick-provisioning playbook
# ---------------------------

# A Simple, straight playbook for quick remote installations.
# You will be asked which hosts to provision before-hand.


- name: 'Supervisor'

  vars_prompt:
    - name: "selected_hosts"
      prompt: "Specify the hosts to provision"
      default: "all"

  hosts: "{{ selected_hosts }}"

  roles:
    - '.'    # The current directory itself is the role

