---

# Integration testing playbook
# ----------------------------

# A playbook for testing and integration.

# It will provision the `test` hosts in the inventory,
# which will, by default, specify the provided vagrant VM.

# This playbook should aim to test the most extensive
# or comprehensive configuration possible for your role.


- name: 'Role integration tests'

  hosts: test

  vars:
    # custom_configuration: value
    supervisor_programs:
      - name: ping
        command: ping -i 10 localhost
        autostart: true
        autorestart: true
    supervisor_events:
      - name: crashmail
        command: crashmail -p program -m alerts@localhost
        events: PROCESS_STATE_EXITED
    supervisor_groups:
      - name: my_group
        programs: ping

  roles:
    - '.'    # The current directory itself is the role

